[tool.poetry]
name = "gemini-projetoab2"
version = "0.1.0"
description = ""
authors = ["Vinicius Cabral  <viniciuscabral26@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
